### ISSUE TITLE
Exit code 22

### ISSUE THREAD

**Issue by jesus-vivas** [lsacera/KiuwanBaselineAction#2]
Hello!
First of all, I want to thank you for this amazing feature, I'm very excited about it!

I'm currently receiving the following trying to use your action:
`
Analysis authorization: STARTED
ERROR running target "analysis.authorization" - Unexpected response status = 403; Reason: Access denied.
com.optimyth.qaking.agent.common.client.kiuwan.KiuwanClientException: Unexpected response status = 403; Reason: Access denied.
	at com.optimyth.qaking.agent.common.client.kiuwan.KiuwanClientException.createResponseStatusException(KiuwanClientException.java:51)
	at com.optimyth.qaking.agent.common.client.kiuwan.KiuwanClientException.createResponseStatusException(KiuwanClientException.java:55)
	at com.optimyth.qaking.agent.common.client.kiuwan.KiuwanRestApiClient.k26(KiuwanRestApiClient.java:820)
	at com.optimyth.qaking.agent.common.client.kiuwan.KiuwanRestApiClient.putApplication(KiuwanRestApiClient.java:243)
	at com.optimyth.qaking.agent.common.client.kiuwan.KiuwanRestApiClient.putApplication(KiuwanRestApiClient.java:225)
	at com.optimyth.qaking.agent.common.client.AgentCloudClient.getApplicationInfo(AgentCloudClient.java:209)
	at com.optimyth.qaking.agent.analyzer.tasks.client.AnalysisAuthorizationTask.execute(AnalysisAuthorizationTask.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:357)
	at org.apache.tools.ant.Target.performTasks(Target.java:385)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1329)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1298)
	at com.optimyth.ant.RunTargetTask.execute(RunTargetTask.java:32)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:62)
	at com.optimyth.ant.IfTask.execute(IfTask.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:134)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at com.optimyth.ant.TryCatchTask.execute(TryCatchTask.java:142)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:357)
	at org.apache.tools.ant.Target.performTasks(Target.java:385)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1329)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1298)
	at com.optimyth.qaking.agent.analyzer.ConsoleLauncher.k26(ConsoleLauncher.java:392)
	at com.optimyth.qaking.agent.analyzer.ConsoleLauncher.main(ConsoleLauncher.java:81)
Kiuwan Local Analyzer found a problem in the current analysis:
Error returned from Kiuwan: Unexpected response status = 403; Reason: Access denied.
Please check Kiuwan Local Analyzer troubleshooting guide for details on how to solve this issue:
https://www.kiuwan.com/docs/display/K5/Troubleshooting
Exit code = 22
ERROR running target "run" - Unexpected response status = 403; Reason: Access denied.
com.optimyth.qaking.agent.common.client.kiuwan.KiuwanClientException: Unexpected response status = 403; Reason: Access denied.
	at com.optimyth.qaking.agent.common.client.kiuwan.KiuwanClientException.createResponseStatusException(KiuwanClientException.java:51)
	at com.optimyth.qaking.agent.common.client.kiuwan.KiuwanClientException.createResponseStatusException(KiuwanClientException.java:55)
	at com.optimyth.qaking.agent.common.client.kiuwan.KiuwanRestApiClient.k26(KiuwanRestApiClient.java:820)
	at com.optimyth.qaking.agent.common.client.kiuwan.KiuwanRestApiClient.putApplication(KiuwanRestApiClient.java:243)
	at com.optimyth.qaking.agent.common.client.kiuwan.KiuwanRestApiClient.putApplication(KiuwanRestApiClient.java:225)
	at com.optimyth.qaking.agent.common.client.AgentCloudClient.getApplicationInfo(AgentCloudClient.java:209)
	at com.optimyth.qaking.agent.analyzer.tasks.client.AnalysisAuthorizationTask.execute(AnalysisAuthorizationTask.java:68)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:357)
	at org.apache.tools.ant.Target.performTasks(Target.java:385)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1329)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1298)
	at com.optimyth.ant.RunTargetTask.execute(RunTargetTask.java:32)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:62)
	at com.optimyth.ant.IfTask.execute(IfTask.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:134)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at com.optimyth.ant.TryCatchTask.execute(TryCatchTask.java:142)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:288)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:105)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:357)
	at org.apache.tools.ant.Target.performTasks(Target.java:385)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1329)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1298)
	at com.optimyth.qaking.agent.analyzer.ConsoleLauncher.k26(ConsoleLauncher.java:392)
	at com.optimyth.qaking.agent.analyzer.ConsoleLauncher.main(ConsoleLauncher.java:81)
KLA return code: 22
`

From what I have gathered it is a problem related to not having access or permission to run any of the files from kiuwan cli. Is there any chmod missing, perhaps? Am I missing a step?

Thanks in advance.
Kind regards,
David.

**Comment by lsacera** [comment]
Hello David:
Seems like do you do not have access to the Kiuwan server with the user and password provided.
Have you tried to login into kiuwan.com with your credentials.
If that is OK, maybe the problem is you do not have permissions to create new applications in the kiuwan server or maybe you do not have permissions to analyse and application.

Remember this task do the analysis within Github, but upload the results to the kiuwan server, and you need a kiuwan account to be able to see the result of the security analysis. 
Hope this helps.

**Comment by jesus-vivas** [comment]
You wer absolutely right, it was permissions. Thank you very much for your help and keep up the good work!!
